# 20240326筆記

[關於阿姆斯壯數 #040](https://zerojudge.tw/ShowProblem?problemid=a040)

In [1]:
def is_armstrong_number(num):
    # 计算数字的位数
    num_str = str(num)
    num_digits = len(num_str)
    
    # 计算每个位上的数字的n次幂之和
    sum_of_digits = sum(int(digit)**num_digits for digit in num_str)
    
    # 如果数字等于其每个位上的数字的n次幂之和，则它是阿姆斯特朗数
    return num == sum_of_digits

def find_armstrong_numbers(start, end):
    armstrong_numbers = []
    for num in range(start, end + 1):
        if is_armstrong_number(num):
            armstrong_numbers.append(num)
    return armstrong_numbers

def main():
    try:
        start = int(input("請輸入起始數字："))
        end = int(input("請輸入結束數字："))
        
        if start >= end:
            print("起始數字必須小於結束數字。")
            return
        
        armstrong_numbers = find_armstrong_numbers(start, end)
        
        if armstrong_numbers:
            print("這之間的阿姆斯壯數有:")
            print(armstrong_numbers)
        else:
            print("這之間沒有阿姆斯壯數。")
    except ValueError:
        print("請輸入有效的整數。")

if __name__ == "__main__":
    main()


請輸入起始數字： 100
請輸入結束數字： 999


這之間的阿姆斯壯數有:
[153, 370, 371, 407]


In [2]:
def is_armstrong_number(num):
    # 计算数字的位数
    num_str = str(num)
    num_digits = len(num_str)
    
    # 计算每个位上的数字的n次幂之和
    sum_of_digits = sum(int(digit)**num_digits for digit in num_str)
    
    # 如果数字等于其每个位上的数字的n次幂之和，则它是阿姆斯特朗数
    return num == sum_of_digits

def find_armstrong_numbers(start, end):
    armstrong_numbers = []
    for num in range(start, end + 1):
        if is_armstrong_number(num):
            armstrong_numbers.append(num)
    return armstrong_numbers

def main():
    try:
        start, end = map(int, input("請輸入兩個數字，中間用空格分開：").split())
        
        if start >= end:
            print("起始數字必須小於結束數字。")
            return
        
        armstrong_numbers = find_armstrong_numbers(start, end)
        
        if armstrong_numbers:
            print("這之間的阿姆斯壯數有:")
            print(armstrong_numbers)
        else:
            print("這之間沒有阿姆斯壯數。")
    except ValueError:
        print("請輸入有效的整數。")

if __name__ == "__main__":
    main()


請輸入兩個數字，中間用空格分開： 100 999


這之間的阿姆斯壯數有:
[153, 370, 371, 407]


In [3]:
try:
    start, end = map(int, input("請輸入兩個數字，中間用空格分開：").split())

    if start >= end:
        print("起始數字必須小於結束數字。")
    else:
        armstrong_numbers = []
        for num in range(start, end + 1):
            num_str = str(num)
            num_digits = len(num_str)
            sum_of_digits = sum(int(digit)**num_digits for digit in num_str)
            if num == sum_of_digits:
                armstrong_numbers.append(num)

        if armstrong_numbers:
            print("這之間的阿姆斯壯數有:")
            print(armstrong_numbers)
        else:
            print("這之間沒有阿姆斯壯數。")
except ValueError:
    print("請輸入有效的整數。")


請輸入兩個數字，中間用空格分開： 100 999


這之間的阿姆斯壯數有:
[153, 370, 371, 407]


In [5]:
try:
    start, end = map(int, input("請輸入兩個數字，中間用空格分開：").split())

    if start >= end:
        print("起始數字必須小於結束數字。")
    else:
        armstrong_numbers = []
        for num in range(start, end + 1):
            num_str = str(num)
            num_digits = len(num_str)
            sum_of_digits = sum(int(digit)**num_digits for digit in num_str)
            if num == sum_of_digits:
                print(num, end=' ')
        print()  # 打印换行符以结束输出
except ValueError:
    print("請輸入有效的整數。")


請輸入兩個數字，中間用空格分開： 10 99


## 阿姆斯壯數

$1634 = 1^4 + 6^4 + 3^4 + 4^4$

In [10]:
def armstrong(n):
    s = str(n)
    total = 0
    c = len(s)
    for i in s:
        total += int(i)**c
    return total==n

In [13]:
m, n = input().split()
for i in range(int(m), int(n)+1):
    if armstrong(i):
        print(i)

 100 999


153
370
371
407


In [16]:
m, n = input().split()
answers = []
for i in range(int(m), int(n)+1):
    if armstrong(i):
        answers.append(i)
answers

 100 999


[153, 370, 371, 407]

In [18]:
m, n = input().split()
answers = []
for i in range(int(m), int(n)+1):
    if armstrong(i):
        answers.append(str(i))
answers

 100 999


['153', '370', '371', '407']

In [19]:
" ".join(answers)

'153 370 371 407'

## 練習 01

請寫一個猜數字的程式。

先用亂數產生一個[1, 5]之間的整數n，再請使用者猜亂數產生什麼樣的數字，如果猜中了，就印出猜對了，不然就印出，猜錯了，正確答案是n。

In [20]:
import random

In [50]:
n = random.randint(1, 5)
x = input("猜猜看，是哪一個數字？")
if int(x)==n:
    print(f"沒錯，答案是{n}!")
else:
    print(f"錯了，答案是{n}!")

猜猜看，是哪一個數字？ 2


沒錯，答案是2!


## 練習 02
請寫一個練習乘法的程式。

先用亂數產生兩個[2, 9]之間的整數m, n，再請使用者輸入mxn的結果，如果算對了，就印出好厲害，不然就印出，正確答案是mxn喔，請繼續努力。

In [57]:
m = random.randint(2, 9)
n = random.randint(2, 9)
x = input(f"請問 {m} x {n} = ？")
if int(x)==m*n:
    print(f"沒錯，答案是 {x}!")
else:
    print(f"錯了，答案是 {m*n}!")

請問 7 x 9 = ？ 64


錯了，答案是63!


## Pandas基礎

* Series
* DataFrame

### Series

In [58]:
data1 = list(range(1, 6))

In [59]:
data1

[1, 2, 3, 4, 5]

In [60]:
data2 = list(range(2, 7))

In [61]:
data2

[2, 3, 4, 5, 6]

In [66]:
import pandas as pd
import numpy as np

In [74]:
series1 = pd.Series(data1)
series2 = pd.Series(data2)

In [67]:
array1 = np.array(data1)
array2 = np.array(data2)

In [65]:
series1

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [68]:
array1

array([1, 2, 3, 4, 5])

In [69]:
series1.values

array([1, 2, 3, 4, 5], dtype=int64)

In [71]:
array1 == series1.values

array([ True,  True,  True,  True,  True])

In [72]:
array1 + array2

array([ 3,  5,  7,  9, 11])

In [75]:
series1 + series2

0     3
1     5
2     7
3     9
4    11
dtype: int64

In [76]:
series1.index = list('abcde')

In [77]:
series1

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [78]:
series2.index = list('bcdef')

In [79]:
series2

b    2
c    3
d    4
e    5
f    6
dtype: int64

In [80]:
series1 + series2

a     NaN
b     4.0
c     6.0
d     8.0
e    10.0
f     NaN
dtype: float64

In [81]:
series1*series2

a     NaN
b     4.0
c     9.0
d    16.0
e    25.0
f     NaN
dtype: float64

In [82]:
series1

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [83]:
series1[0]

C:\Users\Victor\AppData\Local\Temp\ipykernel_6464\2253950659.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  series1[0]


1

In [84]:
series1.iloc[0]

1

In [85]:
series1['a']

1

In [87]:
series1.loc['a']

1

In [88]:
series1

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [90]:
series1.iloc[1:3]

b    2
c    3
dtype: int64

In [91]:
series1.loc['b':'d']

b    2
c    3
d    4
dtype: int64

In [94]:
series1.index = list('abcda')

In [95]:
series1

a    1
b    2
c    3
d    4
a    5
dtype: int64

In [96]:
series1.loc['a']

a    1
a    5
dtype: int64

## 關於數學運算

In [97]:
import math

In [98]:
math.gcd(10, 50)

10

In [99]:
math.lcm(12, 18)

36

In [100]:
math.acos?

Signature: math.acos(x, /)
Docstring:
Return the arc cosine (measured in radians) of x.

The result is between 0 and pi.
Type:      builtin_function_or_method

In [101]:
math.lcm(12, 18, 24)

72

In [109]:
n = input()
if int(n)!=0:
    x = input().split()
    data = []
    for i in range(int(n)):
        data.append(int(x[i]))
    print(math.lcm(*data))

 0


In [110]:
math.gcd(4, 8, 12)

4

In [129]:
def lcm(a, b):
    return a*b//math.gcd(a, b)

In [133]:
import functools

def nlcm(*args):
    return functools.reduce(lcm, args)

In [138]:
def add(a, b):
    return a + b
functools.reduce(add, [1, 2, 3, 4])

10

In [139]:
functools.reduce(lambda a, b: a + b, [1, 2, 3, 4])

10

In [136]:
nlcm(8, 12, 24)

24

In [137]:
math.lcm(8, 12, 24)

24

In [128]:
math.gcd(12, 8, 5)

1

In [120]:
x = [12, 20, 18, 25, 6]

In [121]:
# 回傳 list 長度
len(x)

5

In [122]:
min(x)

6

In [123]:
max(x)

25

In [124]:
sum(x)

81

In [127]:
sum(x)/len(x)

16.2