# 20240326筆記

[關於阿姆斯壯數 #040](https://zerojudge.tw/ShowProblem?problemid=a040)

In [1]:
def is_armstrong_number(num):
    # 计算数字的位数
    num_str = str(num)
    num_digits = len(num_str)
    
    # 计算每个位上的数字的n次幂之和
    sum_of_digits = sum(int(digit)**num_digits for digit in num_str)
    
    # 如果数字等于其每个位上的数字的n次幂之和，则它是阿姆斯特朗数
    return num == sum_of_digits

def find_armstrong_numbers(start, end):
    armstrong_numbers = []
    for num in range(start, end + 1):
        if is_armstrong_number(num):
            armstrong_numbers.append(num)
    return armstrong_numbers

def main():
    try:
        start = int(input("請輸入起始數字："))
        end = int(input("請輸入結束數字："))
        
        if start >= end:
            print("起始數字必須小於結束數字。")
            return
        
        armstrong_numbers = find_armstrong_numbers(start, end)
        
        if armstrong_numbers:
            print("這之間的阿姆斯壯數有:")
            print(armstrong_numbers)
        else:
            print("這之間沒有阿姆斯壯數。")
    except ValueError:
        print("請輸入有效的整數。")

if __name__ == "__main__":
    main()


請輸入起始數字： 100
請輸入結束數字： 999


這之間的阿姆斯壯數有:
[153, 370, 371, 407]


In [2]:
def is_armstrong_number(num):
    # 计算数字的位数
    num_str = str(num)
    num_digits = len(num_str)
    
    # 计算每个位上的数字的n次幂之和
    sum_of_digits = sum(int(digit)**num_digits for digit in num_str)
    
    # 如果数字等于其每个位上的数字的n次幂之和，则它是阿姆斯特朗数
    return num == sum_of_digits

def find_armstrong_numbers(start, end):
    armstrong_numbers = []
    for num in range(start, end + 1):
        if is_armstrong_number(num):
            armstrong_numbers.append(num)
    return armstrong_numbers

def main():
    try:
        start, end = map(int, input("請輸入兩個數字，中間用空格分開：").split())
        
        if start >= end:
            print("起始數字必須小於結束數字。")
            return
        
        armstrong_numbers = find_armstrong_numbers(start, end)
        
        if armstrong_numbers:
            print("這之間的阿姆斯壯數有:")
            print(armstrong_numbers)
        else:
            print("這之間沒有阿姆斯壯數。")
    except ValueError:
        print("請輸入有效的整數。")

if __name__ == "__main__":
    main()


請輸入兩個數字，中間用空格分開： 100 999


這之間的阿姆斯壯數有:
[153, 370, 371, 407]


In [3]:
try:
    start, end = map(int, input("請輸入兩個數字，中間用空格分開：").split())

    if start >= end:
        print("起始數字必須小於結束數字。")
    else:
        armstrong_numbers = []
        for num in range(start, end + 1):
            num_str = str(num)
            num_digits = len(num_str)
            sum_of_digits = sum(int(digit)**num_digits for digit in num_str)
            if num == sum_of_digits:
                armstrong_numbers.append(num)

        if armstrong_numbers:
            print("這之間的阿姆斯壯數有:")
            print(armstrong_numbers)
        else:
            print("這之間沒有阿姆斯壯數。")
except ValueError:
    print("請輸入有效的整數。")


請輸入兩個數字，中間用空格分開： 100 999


這之間的阿姆斯壯數有:
[153, 370, 371, 407]


In [5]:
try:
    start, end = map(int, input("請輸入兩個數字，中間用空格分開：").split())

    if start >= end:
        print("起始數字必須小於結束數字。")
    else:
        armstrong_numbers = []
        for num in range(start, end + 1):
            num_str = str(num)
            num_digits = len(num_str)
            sum_of_digits = sum(int(digit)**num_digits for digit in num_str)
            if num == sum_of_digits:
                print(num, end=' ')
        print()  # 打印换行符以结束输出
except ValueError:
    print("請輸入有效的整數。")


請輸入兩個數字，中間用空格分開： 10 99


## 阿姆斯壯數

$1634 = 1^4 + 6^4 + 3^4 + 4^4$

In [10]:
def armstrong(n):
    s = str(n)
    total = 0
    c = len(s)
    for i in s:
        total += int(i)**c
    return total==n

In [13]:
m, n = input().split()
for i in range(int(m), int(n)+1):
    if armstrong(i):
        print(i)

 100 999


153
370
371
407


In [16]:
m, n = input().split()
answers = []
for i in range(int(m), int(n)+1):
    if armstrong(i):
        answers.append(i)
answers

 100 999


[153, 370, 371, 407]

In [18]:
m, n = input().split()
answers = []
for i in range(int(m), int(n)+1):
    if armstrong(i):
        answers.append(str(i))
answers

 100 999


['153', '370', '371', '407']

In [19]:
" ".join(answers)

'153 370 371 407'

## 練習 01

請寫一個猜數字的程式。

先用亂數產生一個[1, 5]之間的整數n，再請使用者猜亂數產生什麼樣的數字，如果猜中了，就印出猜對了，不然就印出，猜錯了，正確答案是n。

In [20]:
import random

In [50]:
n = random.randint(1, 5)
x = input("猜猜看，是哪一個數字？")
if int(x)==n:
    print(f"沒錯，答案是{n}!")
else:
    print(f"錯了，答案是{n}!")

猜猜看，是哪一個數字？ 2


沒錯，答案是2!


## 練習 02
請寫一個練習乘法的程式。

先用亂數產生兩個[2, 9]之間的整數m, n，再請使用者輸入mxn的結果，如果算對了，就印出好厲害，不然就印出，正確答案是mxn喔，請繼續努力。

In [57]:
m = random.randint(2, 9)
n = random.randint(2, 9)
x = input(f"請問 {m} x {n} = ？")
if int(x)==m*n:
    print(f"沒錯，答案是 {x}!")
else:
    print(f"錯了，答案是 {m*n}!")

請問 7 x 9 = ？ 64


錯了，答案是63!


## Pandas基礎

* Series
* DataFrame

### Series

In [58]:
data1 = list(range(1, 6))

In [59]:
data1

[1, 2, 3, 4, 5]

In [60]:
data2 = list(range(2, 7))

In [61]:
data2

[2, 3, 4, 5, 6]

In [66]:
import pandas as pd
import numpy as np

In [74]:
series1 = pd.Series(data1)
series2 = pd.Series(data2)

In [67]:
array1 = np.array(data1)
array2 = np.array(data2)

In [65]:
series1

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [68]:
array1

array([1, 2, 3, 4, 5])

In [69]:
series1.values

array([1, 2, 3, 4, 5], dtype=int64)

In [71]:
array1 == series1.values

array([ True,  True,  True,  True,  True])

In [72]:
array1 + array2

array([ 3,  5,  7,  9, 11])

In [75]:
series1 + series2

0     3
1     5
2     7
3     9
4    11
dtype: int64

In [76]:
series1.index = list('abcde')

In [77]:
series1

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [78]:
series2.index = list('bcdef')

In [79]:
series2

b    2
c    3
d    4
e    5
f    6
dtype: int64

In [80]:
series1 + series2

a     NaN
b     4.0
c     6.0
d     8.0
e    10.0
f     NaN
dtype: float64

In [81]:
series1*series2

a     NaN
b     4.0
c     9.0
d    16.0
e    25.0
f     NaN
dtype: float64

In [82]:
series1

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [83]:
series1[0]

C:\Users\Victor\AppData\Local\Temp\ipykernel_6464\2253950659.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  series1[0]


1

In [84]:
series1.iloc[0]

1

In [85]:
series1['a']

1

In [87]:
series1.loc['a']

1

In [88]:
series1

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [90]:
series1.iloc[1:3]

b    2
c    3
dtype: int64

In [91]:
series1.loc['b':'d']

b    2
c    3
d    4
dtype: int64

In [94]:
series1.index = list('abcda')

In [95]:
series1

a    1
b    2
c    3
d    4
a    5
dtype: int64

In [96]:
series1.loc['a']

a    1
a    5
dtype: int64

## 關於數學運算

In [97]:
import math

In [98]:
math.gcd(10, 50)

10

In [99]:
math.lcm(12, 18)

36

In [100]:
math.acos?

Signature: math.acos(x, /)
Docstring:
Return the arc cosine (measured in radians) of x.

The result is between 0 and pi.
Type:      builtin_function_or_method

In [101]:
math.lcm(12, 18, 24)

72

In [109]:
n = input()
if int(n)!=0:
    x = input().split()
    data = []
    for i in range(int(n)):
        data.append(int(x[i]))
    print(math.lcm(*data))

 0


In [110]:
math.gcd(4, 8, 12)

4

In [129]:
def lcm(a, b):
    return a*b//math.gcd(a, b)

In [133]:
import functools

def nlcm(*args):
    return functools.reduce(lcm, args)

In [138]:
def add(a, b):
    return a + b
functools.reduce(add, [1, 2, 3, 4])

10

In [139]:
functools.reduce(lambda a, b: a + b, [1, 2, 3, 4])

10

In [136]:
nlcm(8, 12, 24)

24

In [137]:
math.lcm(8, 12, 24)

24

In [128]:
math.gcd(12, 8, 5)

1

In [120]:
x = [12, 20, 18, 25, 6]

In [121]:
# 回傳 list 長度
len(x)

5

In [122]:
min(x)

6

In [123]:
max(x)

25

In [124]:
sum(x)

81

In [127]:
sum(x)/len(x)

16.2

In [140]:
x

[12, 20, 18, 25, 6]

In [141]:
arrayx = np.array(x)

In [142]:
arrayx.mean()

16.2

In [143]:
arrayx.min()

6

In [144]:
arrayx.max()

25

In [147]:
np.median(arrayx)

18.0

In [156]:
arrayx.std()

6.584831053261731

## 使用dict儲存資料

In [163]:
import yfinance as yf
import requests

In [164]:
stocks = [2330, 2454, 2317, 2308, 2303]

In [167]:
session = requests.Session()
session.verify = False
df = yf.download(f'{stocks[0]}.tw', session=session)

C:\Users\Victor\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\urllib3\connectionpool.py:1103: InsecureRequestWarning: Unverified HTTPS request is being made to host 'query2.finance.yahoo.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
[*********************100%%**********************]  1 of 1 completed


In [168]:
data = {}

In [171]:
for i in stocks:
    data[i] = yf.download(f"{i}.tw", session=session)

C:\Users\Victor\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\urllib3\connectionpool.py:1103: InsecureRequestWarning: Unverified HTTPS request is being made to host 'query2.finance.yahoo.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
[*********************100%%**********************]  1 of 1 completed
C:\Users\Victor\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\urllib3\connectionpool.py:1103: InsecureRequestWarning: Unverified HTTPS request is being made to host 'query2.finance.yahoo.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\Victor\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\L

In [173]:
data.keys()

dict_keys([2330, 2454, 2317, 2308, 2303])

In [174]:
data[2330]

Open        High         Low       Close   Adj Close  \
Date                                                                     
2000-01-04   69.649033   69.649033   68.475182   69.649033   34.502377   
2000-01-05   69.649033   71.214043   68.866341   71.214043   35.277641   
2000-01-06   70.822884   71.214043   69.649033   69.649033   34.502377   
2000-01-07   67.301331   68.475182   66.518639   67.692490   33.533150   
2000-01-10   69.649033   70.431351   68.475182   70.040192   34.696148   
...                ...         ...         ...         ...         ...   
2024-03-20  764.000000  769.000000  752.000000  758.000000  758.000000   
2024-03-21  773.000000  784.000000  772.000000  784.000000  784.000000   
2024-03-22  788.000000  789.000000  775.000000  785.000000  785.000000   
2024-03-25  783.000000  788.000000  779.000000  780.000000  780.000000   
2024-03-26  788.000000  792.000000  778.000000  780.000000  780.000000   

                  Volume  
Date                      
2000-01-04  200662336736  
2000-01-05  402466805912  
2000-01-06  197545715802  
2000-01-07  235270344752  
2000-01-10  276171685539  
...                  ...  
2024-03-20      41280325  
2024-03-21      46026103  
2024-03-22      30660820  
2024-03-25      19877101  
2024-03-26      23402702  

[6038 rows x 6 columns]

In [175]:
import pickle

In [176]:
with open('stocks.pkl','wb') as f:
    pickle.dump(data, f)

In [177]:
with open('stocks.pkl','rb') as f:
    data1 = pickle.load(f)

In [178]:
data1[2330]

Open        High         Low       Close   Adj Close  \
Date                                                                     
2000-01-04   69.649033   69.649033   68.475182   69.649033   34.502377   
2000-01-05   69.649033   71.214043   68.866341   71.214043   35.277641   
2000-01-06   70.822884   71.214043   69.649033   69.649033   34.502377   
2000-01-07   67.301331   68.475182   66.518639   67.692490   33.533150   
2000-01-10   69.649033   70.431351   68.475182   70.040192   34.696148   
...                ...         ...         ...         ...         ...   
2024-03-20  764.000000  769.000000  752.000000  758.000000  758.000000   
2024-03-21  773.000000  784.000000  772.000000  784.000000  784.000000   
2024-03-22  788.000000  789.000000  775.000000  785.000000  785.000000   
2024-03-25  783.000000  788.000000  779.000000  780.000000  780.000000   
2024-03-26  788.000000  792.000000  778.000000  780.000000  780.000000   

                  Volume  
Date                      
2000-01-04  200662336736  
2000-01-05  402466805912  
2000-01-06  197545715802  
2000-01-07  235270344752  
2000-01-10  276171685539  
...                  ...  
2024-03-20      41280325  
2024-03-21      46026103  
2024-03-22      30660820  
2024-03-25      19877101  
2024-03-26      23402702  

[6038 rows x 6 columns]

## Scikit-learn 簡介

https://github.com/vcdemy/sklearn

In [179]:
!pip install scikit-learn

Defaulting to user installation because normal site-packages is not writeable
   ---------------------------------------- 0.0/10.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/10.6 MB 640.0 kB/s eta 0:00:17
   ---------------------------------------- 0.1/10.6 MB 812.7 kB/s eta 0:00:13
   ---------------------------------------- 0.1/10.6 MB 1.1 MB/s eta 0:00:10
    --------------------------------------- 0.2/10.6 MB 1.2 MB/s eta 0:00:09
   - -------------------------------------- 0.3/10.6 MB 1.3 MB/s eta 0:00:08
   - -------------------------------------- 0.5/10.6 MB 2.0 MB/s eta 0:00:06
   -- ------------------------------------- 0.6/10.6 MB 1.8 MB/s eta 0:00:06
   --- ------------------------------------ 0.8/10.6 MB 2.4 MB/s eta 0:00:04
   --- ------------------------------------ 1.0/10.6 MB 2.6 MB/s eta 0:00:04
   ----- ---------------------------------- 1.4/10.6 MB 3.3 MB/s eta 0:00:03
   ----- ---------------------------------- 1.5/10.6 MB 3.1 MB/s eta 0:00:03
 

### 檢視資料集

In [180]:
from sklearn.datasets import load_iris

In [181]:
data = load_iris()

In [183]:
data.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [184]:
data.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [189]:
X = data.data

In [190]:
y = data.target

In [191]:
X[0]

array([5.1, 3.5, 1.4, 0.2])

In [192]:
X[-1]

array([5.9, 3. , 5.1, 1.8])

In [193]:
len(X)

150

### 準備訓練集及測試集資料

In [194]:
from sklearn.model_selection import train_test_split

In [195]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=987)

### 使用SVC做分類

#### 1. 載入模型

In [196]:
from sklearn.svm import SVC

#### 2. 建立模型

In [197]:
clf = SVC()

#### 3. 訓練模型

In [198]:
clf.fit(X_train, y_train)

SVC()

#### 4. 評估模型

In [199]:
clf.score(X_test, y_test)

0.9666666666666667

#### 5. 使用模型

In [200]:
clf.predict([[5, 2, 4, 3]])

array([2])

In [201]:
data.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [203]:
clf.predict(X_test[:10])

array([0, 0, 0, 1, 0, 0, 0, 0, 1, 0])

In [204]:
y_test[:10]

array([0, 0, 0, 1, 0, 0, 0, 0, 1, 0])

### 使用RandomForest來做分類

In [207]:
# 1. 載入模型
from sklearn.ensemble import RandomForestClassifier

# 2. 建立模型
clf = RandomForestClassifier()

# 3. 訓練模型
clf.fit(X_train, y_train)

# 4. 評估模型
clf.score(X_test, y_test)

0.9333333333333333

In [212]:
clf.score(X_train, y_train)

1.0

In [210]:
# 5. 使用模型
clf.predict(X_test)

array([0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 2, 2, 1, 1, 1, 0, 1, 1, 2, 1, 0, 1,
       2, 0, 1, 1, 0, 2, 0, 2])

In [211]:
y_test

array([0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 2, 2, 1, 1, 1, 0, 2, 1, 2, 1, 0, 1,
       2, 0, 1, 1, 0, 2, 0, 1])

In [217]:
from sklearn.model_selection import cross_val_score

In [219]:
clf1 = SVC()
clf2 = RandomForestClassifier()

In [220]:
cross_val_score(clf1, X, y, cv=10).mean()

0.9733333333333334

In [221]:
cross_val_score(clf2, X, y, cv=10).mean()

0.96

### XGBoost使用簡介

In [222]:
!pip install xgboost

Defaulting to user installation because normal site-packages is not writeable
   ---------------------------------------- 0.0/99.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/99.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/99.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/99.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/99.8 MB 217.9 kB/s eta 0:07:38
   ---------------------------------------- 0.0/99.8 MB 195.7 kB/s eta 0:08:30
   ---------------------------------------- 0.1/99.8 MB 261.4 kB/s eta 0:06:22
   ---------------------------------------- 0.1/99.8 MB 327.7 kB/s eta 0:05:05
   ---------------------------------------- 0.1/99.8 MB 327.7 kB/s eta 0:05:05
   ---------------------------------------- 0.1/99.8 MB 327.7 kB/s eta 0:05:05
   ---------------------------------------- 0.2/99.8 MB 509.6 kB/s eta 0:03:16
   ---------------------------------------- 0.2/99.8 MB 509.6 kB/s eta 0:03:16
   -------

In [224]:
from xgboost import XGBClassifier
clf = XGBClassifier()
clf.fit(X_train, y_train)
clf.score(X_test, y_test)

0.9333333333333333

In [225]:
from xgboost import XGBClassifier
clf = XGBClassifier(n_estimators=2, max_depth=2, learning_rate=1, objective='binary:logistic')
clf.fit(X_train, y_train)
clf.score(X_test, y_test)

0.9333333333333333